server:
  port: 8085

jwt:
  secret: ${JWT_SECRET:MPM378geHGPiW5UIWqrTNgUZtYXYIMOYqAaGb4abRo8=}

spring:
  cloud:
    gateway:
      routes:
        - id: bms-authuser-service
          uri: lb://BMS-AUTHUSER-SERVICE
          predicates:
            - Path=/bms/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: transaction-service
          uri: lb://BMS-TRANSACTIONMANAGEMENT-SERVICE
          predicates:
            - Path=/transactions/v1/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: transactionCircuitBreaker
                fallbackUri: forward:/fallback/transaction

        - id: account-service
          uri: lb://BMS-ACCOUNTMANAGE-SERVICE
          predicates:
            - Path=/accounts/v1/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: accountCircuitBreaker
                fallbackUri: forward:/fallback/account

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
